from pathlib import Path

RUTA_BASE_DATOS = Path("datos_entrenamiento")

DIRECTORIOS_COMANDOS = {
    "COMANDO_1": [RUTA_BASE_DATOS / "comando_1", RUTA_BASE_DATOS / "A"],
    "COMANDO_2": [RUTA_BASE_DATOS / "comando_2", RUTA_BASE_DATOS / "B"],
    "COMANDO_3": [RUTA_BASE_DATOS / "comando_3", RUTA_BASE_DATOS / "C"],
}

ETIQUETAS_COMANDOS = {
    "COMANDO_1": "segmentar",
    "COMANDO_2": "comprimir",
    "COMANDO_3": "cifrar",
}

FRECUENCIA_MUESTREO_OBJETIVO = 16000
N_FFT = 4096
NUMERO_SUBBANDAS = 16
VENTANA = "hamming"

FRECUENCIA_CORTE_PB = 3500
ORDEN_FILTRO = 4
PREENFASIS_ALPHA = 0.97

UMBRAL_ENERGIA_SILENCIO = 0.01
MARGEN_SILENCIO_MS = 100

ARCHIVO_UMBRALES = Path("umbrales_comandos.json")

DURACION_GRABACION_SEGUNDOS = 1.0
